# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'COMBI.ui'
##
## Created by: Qt User Interface Compiler version 6.5.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(866, 693)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(19, 104, 53, 16))
        font = QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 138, 53, 16))
        self.label_13.setFont(font)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 175, 53, 16))
        self.label_11.setFont(font)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 211, 53, 16))
        self.label_15.setFont(font)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 247, 53, 16))
        self.label_12.setFont(font)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 284, 53, 16))
        self.label_10.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 320, 53, 16))
        self.label_2.setFont(font)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 356, 53, 16))
        self.label_4.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 393, 53, 16))
        self.label_3.setFont(font)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 429, 53, 16))
        self.label.setFont(font)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 465, 53, 16))
        self.label_8.setFont(font)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 502, 53, 16))
        self.label_7.setFont(font)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 538, 53, 16))
        self.label_5.setFont(font)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 574, 53, 16))
        self.label_9.setFont(font)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 611, 53, 16))
        self.label_6.setFont(font)
        self.Second = QLineEdit(self.centralwidget)
        self.Second.setObjectName(u"Second")
        self.Second.setGeometry(QRect(212, 21, 111, 25))
        self.Second.setFont(font)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(331, 22, 16, 22))
        font1 = QFont()
        font1.setPointSize(12)
        self.label_17.setFont(font1)
        self.start = QPushButton(self.centralwidget)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(400, 60, 91, 24))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(21, 21, 188, 22))
        self.label_16.setFont(font1)
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(80, 95, 731, 551))
        self.layoutWidget.setFont(font1)
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.Card38 = QLineEdit(self.layoutWidget)
        self.Card38.setObjectName(u"Card38")
        self.Card38.setFont(font1)
        self.Card38.setLayoutDirection(Qt.LeftToRight)

        self.verticalLayout.addWidget(self.Card38)

        self.Card44 = QLineEdit(self.layoutWidget)
        self.Card44.setObjectName(u"Card44")
        self.Card44.setFont(font1)

        self.verticalLayout.addWidget(self.Card44)

        self.Card46 = QLineEdit(self.layoutWidget)
        self.Card46.setObjectName(u"Card46")
        self.Card46.setFont(font1)

        self.verticalLayout.addWidget(self.Card46)

        self.Card48 = QLineEdit(self.layoutWidget)
        self.Card48.setObjectName(u"Card48")
        self.Card48.setFont(font1)

        self.verticalLayout.addWidget(self.Card48)

        self.Card49 = QLineEdit(self.layoutWidget)
        self.Card49.setObjectName(u"Card49")
        self.Card49.setFont(font1)

        self.verticalLayout.addWidget(self.Card49)

        self.Card50 = QLineEdit(self.layoutWidget)
        self.Card50.setObjectName(u"Card50")
        self.Card50.setFont(font1)

        self.verticalLayout.addWidget(self.Card50)

        self.Card51 = QLineEdit(self.layoutWidget)
        self.Card51.setObjectName(u"Card51")
        self.Card51.setFont(font1)

        self.verticalLayout.addWidget(self.Card51)

        self.Card53 = QLineEdit(self.layoutWidget)
        self.Card53.setObjectName(u"Card53")
        self.Card53.setFont(font1)

        self.verticalLayout.addWidget(self.Card53)

        self.Card54 = QLineEdit(self.layoutWidget)
        self.Card54.setObjectName(u"Card54")
        self.Card54.setFont(font1)

        self.verticalLayout.addWidget(self.Card54)

        self.Card56 = QLineEdit(self.layoutWidget)
        self.Card56.setObjectName(u"Card56")
        self.Card56.setFont(font1)

        self.verticalLayout.addWidget(self.Card56)

        self.Card57 = QLineEdit(self.layoutWidget)
        self.Card57.setObjectName(u"Card57")
        self.Card57.setFont(font1)

        self.verticalLayout.addWidget(self.Card57)

        self.Card59 = QLineEdit(self.layoutWidget)
        self.Card59.setObjectName(u"Card59")
        self.Card59.setFont(font1)

        self.verticalLayout.addWidget(self.Card59)

        self.Card61 = QLineEdit(self.layoutWidget)
        self.Card61.setObjectName(u"Card61")
        self.Card61.setFont(font1)

        self.verticalLayout.addWidget(self.Card61)

        self.Card65 = QLineEdit(self.layoutWidget)
        self.Card65.setObjectName(u"Card65")
        self.Card65.setFont(font1)

        self.verticalLayout.addWidget(self.Card65)

        self.Card68 = QLineEdit(self.layoutWidget)
        self.Card68.setObjectName(u"Card68")
        self.Card68.setFont(font1)

        self.verticalLayout.addWidget(self.Card68)

        self.clear = QPushButton(self.centralwidget)
        self.clear.setObjectName(u"clear")
        self.clear.setGeometry(QRect(310, 640, 201, 31))
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(False)
        font2.setItalic(False)
        font2.setUnderline(False)
        font2.setStrikeOut(False)
        font2.setKerning(True)
        self.clear.setFont(font2)
        self.clear.setAutoDefault(False)
        self.clear.setFlat(False)
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(210, 60, 181, 23))
        font3 = QFont()
        font3.setPointSize(10)
        self.comboBox.setFont(font3)
        self.stop = QPushButton(self.centralwidget)
        self.stop.setObjectName(u"stop")
        self.stop.setGeometry(QRect(500, 60, 91, 24))
        self.copy = QPushButton(self.centralwidget)
        self.copy.setObjectName(u"copy")
        self.copy.setGeometry(QRect(600, 60, 91, 24))
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(399, 21, 242, 22))
        self.label_18.setFont(font1)
        self.coordinate = QLineEdit(self.centralwidget)
        self.coordinate.setObjectName(u"coordinate")
        self.coordinate.setGeometry(QRect(647, 21, 164, 25))
        self.coordinate.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 866, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Card 38", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Card 44", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Card 46", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Card 48", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Card 49", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Card 50", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Card 51", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Card 53", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Card 54", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Card 56", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Card 57", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Card 59", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Card 61", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Card 65", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Card 68", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"S", None))
        self.start.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Wait time to high position:", None))
        self.clear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Card 38", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Card 44", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Card 46", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"Card 48", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"Card 49", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"Card 50", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("MainWindow", u"Card 51", None))
        self.comboBox.setItemText(7, QCoreApplication.translate("MainWindow", u"Card 53", None))
        self.comboBox.setItemText(8, QCoreApplication.translate("MainWindow", u"Card 54", None))
        self.comboBox.setItemText(9, QCoreApplication.translate("MainWindow", u"Card 56", None))
        self.comboBox.setItemText(10, QCoreApplication.translate("MainWindow", u"Card 57", None))
        self.comboBox.setItemText(11, QCoreApplication.translate("MainWindow", u"Card 59", None))
        self.comboBox.setItemText(12, QCoreApplication.translate("MainWindow", u"Card 61", None))
        self.comboBox.setItemText(13, QCoreApplication.translate("MainWindow", u"Card 65", None))
        self.comboBox.setItemText(14, QCoreApplication.translate("MainWindow", u"Card 68", None))

        self.stop.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.copy.setText(QCoreApplication.translate("MainWindow", u"COPY", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Coordinates of the CLEAR button\uff1a", None))
    # retranslateUi

